[package]
name = "rust-lightning-bitcoinrpc"
version = "0.0.1"
authors = ["Matt Corallo <git@bluematt.me>"]
build = "build.rs"

[dependencies]
bitcoin = "0.14"
bitcoin-bech32 = "0.7"
bitcoin_hashes = { git = "https://github.com/rust-bitcoin/bitcoin_hashes" }
lightning = "0.0.6"
lightning-invoice = { git = "https://github.com/rust-bitcoin/rust-lightning-invoice" }
secp256k1 = "0.11"
hyper = "0.12"
tokio-io = "0.1"
tokio-fs = "0.1"
tokio-codec = "0.1"
futures = "0.1"
serde = "1"
serde_json = "1"
serde_derive = "1"
rand = "0.4"
tokio = "0.1"
bytes = "0.4"
base64 = "0.9"
rust-crypto = "0.2"

[build-dependencies]
gcc = "0.3"

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"
